<body bgcolor="#f0f0f8">
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="heading">
<tr bgcolor="#6622aa">
<td valign=bottom>&nbsp;<br>
<font color="#ffffff" face="helvetica, arial">&nbsp;<br><big><big><strong>ValueError</strong></big></big></font></td
><td align=right valign=bottom
><font color="#ffffff" face="helvetica, arial">Python 3.8.12: /nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/bin/python<br>Mon Dec 19 17:29:20 2022</font></td></tr></table>
    
<p>A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.</p>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file:///home/runner/Saudecom/projeto/cgi-bin/agua.py">/home/runner/Saudecom/projeto/cgi-bin/agua.py</a> in <strong>&lt;module&gt;</strong></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;&nbsp;4</small>&nbsp;cgitb.enable(display=0,&nbsp;logdir="./")<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;&nbsp;5</small>&nbsp;form&nbsp;=&nbsp;cgi.FieldStorage()<br>
</tt></font></td></tr>
<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;&nbsp;&nbsp;6</small>&nbsp;peso&nbsp;=&nbsp;float(form.getvalue('var1'))<br>
</tt></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;&nbsp;7</small>&nbsp;print("Content-type:text/html\n\n")<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;&nbsp;8</small>&nbsp;print("&lt;html&gt;")<br>
</tt></font></td></tr>
<tr><td><small><font color="#909090">peso <em>undefined</em>, <em>builtin</em> <strong>float</strong>&nbsp;= &lt;class 'float'&gt;, <strong>form</strong>&nbsp;= FieldStorage(None, None, [MiniFieldStorage('var1', '54,5'), MiniFieldStorage('submit', 'Enviar')]), form.<strong>getvalue</strong>&nbsp;= &lt;bound method FieldStorage.getvalue of FieldStor... '54,5'), MiniFieldStorage('submit', 'Enviar')])&gt;</font></small></td></tr></table><p><strong>ValueError</strong>: could not convert string to float: '54,5'
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>args&nbsp;=
("could not convert string to float: '54,5'",)
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>with_traceback&nbsp;=
&lt;built-in method with_traceback of ValueError object&gt;


<!-- The above is a description of an error in a Python program, formatted
     for a Web browser because the 'cgitb' module was enabled.  In case you
     are not reading this in a Web browser, here is the original traceback:

Traceback (most recent call last):
  File "/home/runner/Saudecom/projeto/cgi-bin/agua.py", line 6, in &lt;module&gt;
    peso = float(form.getvalue('var1'))
ValueError: could not convert string to float: '54,5'

-->
